### ISSUE TITLE
EpiModel Checklist: v2.2.0

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#556]
**Periodically (not every release)** 📆 
- [ ] Run code coverage analysis using `library("covr"); report(package_coverage())`
- [x] Delint package with `lintr::lint_package`. Can ignore snake case variable warnings. 

**Before publishing on CRAN** 🔨 
- [x] Do a global find for `TODO`. Update as necessary.
- [x] Run tests on linux, windows, and mac using `rhub::check_for_cran(show_status = FALSE)`
- [x] Update version and date on `EpiModel-package.R` file and DESCRIPTION
- [x] Update NEWS
- [x] Build source package
- [x] Tag release
- [x] Upload to CRAN

**After published on CRAN** 💅 
- [x] Update README: badges, v#, DOI
- [ ] _If necessary:_ Update tutorials for any major changes
- [x] Updates to http://epimodel.org/
- [ ] _If necessary:_ redeploy shiny apps to http://statnet.shinyapps.io/
- [ ] _Optional:_ Announce new version on twitter
- [x] Create new release milestone
- [x] Create new release CRAN checklist issue
- [x] Close current issue milestone and checklist issue
