### ISSUE TITLE
synopsis of pull requests

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#858]
Just an informational issue to summarize the status and relationships of the current PRs on EpiModel:

- [x] PR #834 can probably be closed without merging since egor was updated on CRAN
- [x] PR #849 (directly on the main branch) adds the `netsim_dat` class, updates documentation, and makes `get_network` and `set_network` generics, closing issue #390
- [x] PR #853 (stacked on #849) adds the `icm_dat` class (for consistency) and updates documentation, closing issue #850
- [x] PR #825 (directly on the main branch) is a larger pull request that has already had multiple other PRs merged into it; those updates depend on `master` versions of statnet packages, as we have previously discussed
- [x] PR #845 (stacked on #825) adds a function to depart nodes from the dat object, closing issue #598 
- [x] PR #855 (stacked on #845) adds a function to arrive nodes to the dat object, closing issue #847
- [x] PR #854 (stacked on #845) deprecates the deleteAttr function in favor of delete_attr, closing issue #846
- [x] the final two PRs #856, #857 (stacked on #845 and #855, respectively) are just minor documentation updates for the depart_nodes and arrive_nodes functions; they should be merged when (and only when) #849 is merged, to keep the documentation consistent
- [x] Where appropriate there are corresponding pull requests on EpiModelHIV-p (EpiModel/EpiModelHIV-p#259, EpiModel/EpiModelHIV-p#260, and EpiModel/EpiModelHIV-p#261) and EpiModelCOVID (all updates are in the pull request EpiModel/EpiModelCOVID#35).

**Comment by AdrienLeGuillou** [comment]
I think we can close this as all is done. 
@smjenness you can re-open if I missed something
