### ISSUE TITLE
EpiModel Checklist: v2.5.1

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#919]
**Periodically (not every release)** 📆 
- [ ] Run code coverage analysis using `covr::report(package_coverage())`
- [ ] Delint package with `lintr::lint_package`.

**Before publishing on CRAN** 🔨 
- [ ] Do a global find for `TODO`. Update as necessary.
- [ ] Remove any Github Remotes fields from DESCRIPTION. Github Actions should be rerun and clear.
- [ ]  Check all URLs with `urlchecker::url_check()`
- [ ] Update version and date on `EpiModel-package.R` file and DESCRIPTION
- [ ] Update NEWS
- [ ] Build source package
- [ ] Upload to CRAN

**After published on CRAN** 💅 
- [ ] Tag release
- [ ] Update README: badges, v#, DOI
- [ ] _If necessary:_ Update tutorials for any major changes
- [ ] Updates to http://epimodel.org/
- [ ] _If necessary:_ redeploy shiny apps to http://statnet.shinyapps.io/
- [ ] Create new release milestone
- [ ] Create new release CRAN checklist issue
- [ ] Close current issue milestone and checklist issue
